### ISSUE TITLE
NullPointerException sur tokens se terminant par 'ch'

### ISSUE THREAD

**Issue by labsdul** [hcapitaine/french-phonetic-analyser#4]
Bonjour,

Nous avons essayé de tester le plugin pour indexer des pahonèmes dans Elasticsearch, mais en prenant quelques cas de tests (via l'API Analyze), nous sommes tombés (par chance ?) sur un terme qui provoque une NPE dans l'encodeur :

```
GET _analyze
{
  "tokenizer":  "standard",
  "filter": [
    "french_phonetic"
   ],
  "text" : "varech"
}
```

La réponse d'ES est la suivante : 

```json
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[q7VZOCz][172.17.0.21:9300][indices:admin/analyze[s]]"
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```
La log d'erreur d'Elasticsearch indique une erreur sur (Encoder.java:114) :

```
[2018-11-27T13:59:19,601][WARN ][r.suppressed ] path: /_analyze, params: {}
org.elasticsearch.transport.RemoteTransportException: [q7VZOCz][172.17.0.21:9300][indices:admin/analyze[s]]
Caused by: java.lang.NullPointerException
at com.galerieslafayette.analyzer.Encoder.operatePhonetic(Encoder.java:114) ~[?:?]
at com.galerieslafayette.analyzer.Encoder.operatePhonetic(Encoder.java:215) ~[?:?]
at com.galerieslafayette.analyzer.Encoder.operatePhonetic(Encoder.java:231) ~[?:?]
at com.galerieslafayette.analyzer.Encoder.operatePhonetic(Encoder.java:231) ~[?:?]
at com.galerieslafayette.analyzer.Encoder.operatePhonetic(Encoder.java:231) ~[?:?]
at com.galerieslafayette.index.analysis.FrenchPhoneticAnalyzer.encode(FrenchPhoneticAnalyzer.java:105) ~[?:?]
at com.galerieslafayette.index.analysis.FrenchPhoneticAnalyzer.incrementToken(FrenchPhoneticAnalyzer.java:49) ~[?:?] 
```

En rajoutant en vitesse des System.out.println() pour débugger et un petit cas de test , il semblerait que ce charAt(tail, 1) soit évalué à null dans le test du if(), ce qui provoque la NPE. Plus concrètement, avec ces sysout :

```java
//CH followed by 2 vowels as K
if(VOWELS.contains(charAt(tail, 1)) && VOWELS.contains(charAt(tail, 2))){
    return operatePhonetic(acc +'K', charAt(tail, 1), substring(tail, 2, tail.length()));
} else {
    //CHR / CHL as KR / KL
    System.out.println("==================================");
    System.out.println("acc="+acc);
    System.out.println("c="+c);
    System.out.println("tail="+tail);
    System.out.println("charAt(tail, 1)="+charAt(tail, 1));
    System.out.println("VOWELS.contains(charAt(tail, 2))="+VOWELS.contains(charAt(tail, 2)));

    if((charAt(tail, 1) == 'R' || charAt(tail, 1) == 'L') && VOWELS.contains(charAt(tail, 2))){
        return operatePhonetic(acc +'K', charAt(tail, 1), substring(tail, 2, tail.length()));
    }
    return operatePhonetic(acc +"C", charAt(tail, 0), substring(tail, 1, tail.length()));
}
```

Et le cas de test suivant : 

```java
@Test
    public void testNpe() {
        FrenchPhoneticAnalyzer frenchPhonetic = new FrenchPhoneticAnalyzer(new FakeTokenStream());
        List<String> encode = frenchPhonetic.encode("varech");
        Assertions.assertThat(encode).containsOnly("VAR2K");
    }
```

On obtient bien la même NPE, avec les infos suivantes : 

```
==================================
acc=2
c=C
tail=H
charAt(tail, 1)=null
VOWELS.contains(charAt(tail, 2))=false

```

**Comment by hcapitaine** [comment]
Corrigé.

**Comment by hcapitaine** [comment]
Merci en tout cas pour le retour aussi détaillé

**Comment by labsdul** [comment]
Je retourne les remerciements. J'ai rarement vu une correction aussi rapide, c'était sacrément appréciable ! :)
